config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all					
	end	
	def new
		@product = Product.new	
		@name = "Crear"	
	end
	def create
		@product = Product.new(product_params)		
		if @product.save 
			redirect_to products_path
		else
			render :new		
		end
	end
	def edit
		@product = Product.find(params[:id])
		@name = "Actualizar"	
	end
	def update
		product = Product.find(params[:id])
		product.update(product_params)
		redirect_to products_path
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy
		redirect_to products_path
	end
	private
		def product_params		
			params.require(:product).permit(:name, :price, category_ids:[])

		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductosV1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container" style="margin-top: 50px;">
  		<div class="row">
  			<%= yield %>
  		</div>
  	</div>    
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<div class="form-group">
		<%= f.label(:name, "Nombre") %>		  		
		<%= f.text_field :name %>
	</div>
	<div class="form-group">
		<%= f.label(:price, "Precio") %>
		 <%= f.number_field :price, step: 0.05 %>
	</div>
	<div class="form-group">
	  	<%= collection_check_boxes(:product, :category_ids, Category.all, :id, :name) %>
	</div>
	<div class="form-group">
	 	<%= f.submit @name, class: "btn btn-primary" %>	
	</div>
<% end %>	

app/views/products/edit.html.erb
<div class="col-sm-6 container">
		<h1>Actualizar Producto</h1>
		<%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="space-beetwen">
  <h1>Productos</h1><br>
  <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary" %>
</div>
<table class="table" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Categorías</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  	<% @products.each do |product| %>
    <tr>
      <th scope="row"><%= product.name %></th>
      <td><%= product.price %></td>
      <td>
        
        <% if product.categories.count.eql?(0) %>
            <%= "" %>
        <% elsif product.categories.count.eql?(1) %>
            <%= product.categories[0].name  %>
        <% else %>
          <% arr = [] %>
          <%  product.categories.each_with_index do |x, y| %>
             <% arr[y] = x.name %>
          <% end %>
            <%= "#{arr[0...-1].join(", ")} y #{arr[-1]}." %>
      <% end %></td>
      <td><%= link_to "Editar", edit_product_path(product) %>     <%= link_to "Eliminar", product_path(product), method: :delete %></td>      
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="col-sm-6 container">
		<h1>Nuevo Producto</h1>
		<%= render 'form' %>
</div>